### ISSUE TITLE
paf2chain creates invalid chain file

### ISSUE THREAD

**Issue by diekhans** [AndreaGuarracino/paf2chain#3]
Converting the attached PAF creates a chain file that the UCSC tools find invalid:

```
% chainToPslBasic problem.chain.gz /dev/null
t end mismatch 4836956 vs 4837101 line 11 of problem.chain.gz
```

[problem.chain.gz](https://github.com/AndreaGuarracino/paf2chain/files/9736008/problem.chain.gz)

**Comment by diekhans** [comment]
I meant to attach the PAF
[problem.paf.gz](https://github.com/AndreaGuarracino/paf2chain/files/9736163/problem.paf.gz)

**Comment by AndreaGuarracino** [comment]
Hi @diekhans, your input PAF has no alignment information, that is no CIGAR strings. In this case, `paf2chain` generates "fake CIGAR strings" by considering query and target fully aligned. There was a problem when query and target have different lengths. Now, `liftOver` is happy with the generated CHAIN file.

**Comment by diekhans** [comment]
Thanks Andrea!!

works great
